### ISSUE TITLE
GNURadio 3.7.10

### ISSUE THREAD

**Issue by Christoph142** [gnieboer/GNURadio_Windows_Build_Scripts#12]
Thanks for providing this easy way of using GNURadio on Windows. I'm using it on Win7 and it works just fine (except for an error with the window icon when running flow graphs). Would you mind updating it to version 3.7.10? :)

**Comment by gnieboer** [comment]
I will Christoph... I've been on holiday and moving house, so it will
probably not be until the end of the month before I do another release.

Geof

**Comment by Christoph142** [comment]
Great. Take your time. Again, thanks for your work! :)

**Comment by Christoph142** [comment]
... of which month? :stuck_out_tongue_closed_eyes: 
Just kidding. Only a friendly reminder for you ;)

**Comment by gnieboer** [comment]
I was ready to go, but then heard 3.7.10.1 was around the corner.  I will
do a build this weekend w/ 3.7.10.1.

Geof

**Comment by gnieboer** [comment]
Done!

**Comment by Christoph142** [comment]
Works great so far. Thanks a lot Geof! :)

_(Note: You might want to update or remove the outdated version number in the header of http://www.gcndevelopment.com/gnuradio/downloads.htm)_
