### ISSUE TITLE
libpng version out of date, fails build script

### ISSUE THREAD

**Issue by kegilbert** [gnieboer/GNURadio_Windows_Build_Scripts#18]
getPackage in Setup.ps1 fails when trying to fetch libpng-1.6.21, current version hosted is 1.6.28. Updating the path worked when running the script.

**Comment by gnieboer** [comment]
Yep, will be in the next update, which will be released soon based on
3.7.10.2 being near final.

**Comment by kegilbert** [comment]
Awesome, thanks! Feel free to close this.
