### ISSUE TITLE
Check ${env:Path} for requirements, not ${env:ProgramFiles(x86)}

### ISSUE THREAD

**Issue by naikrovek** [gnieboer/GNURadio_Windows_Build_Scripts#25]
Not everyone installs things where you do.  

Not everyone *installs* things.  I prefer portable deployments because I carry a 512GB disk around with me.

**Comment by gnieboer** [comment]
This is a duplicate of #3 .  Will consider as a future enhancement.  In the meantime, just comment out the preq check's if you are certain the portable deployment will work.

**Comment by naikrovek** [comment]
Whoops!  I'll close if it's a dupe.  Apologies.

**Comment by naikrovek** [comment]
Duplicate of #3 .  Closing.
