### ISSUE TITLE
Server with file downloads can't be accessed.

### ISSUE THREAD

**Issue by ggamble22** [gnieboer/GNURadio_Windows_Build_Scripts#30]
The file downloads from http://www.gcndevelopment.com/gnuradio/downloads/ do not work at the moment. The reason I need to build from source in the first place is because the drivers for the USRP are out of data. When I try to run software it says fpga firmware 5.1 is needed but it has version 6.0.

**Comment by dkozel** [comment]
@ggamble22 If your application doesn't need the latest UHD features you can load the older FPGA image onto your USRP. If you want to go that route I can assist.
http://files.ettus.com/manual/page_usrp2.html#usrp2_loadflash

Emailing the usrp-users mail list or support@ettus.com would be the best place to talk though as that wouldn't be a problem with the Windows Build Scripts.

**Comment by ggamble22** [comment]
I am probably going to move to a Linux build and see if I have better luck with it. I do not believe I need the latest version, the question is can I load older firmware on the USRP? If that is the case then I won't need to do this in the first place.

**Comment by dkozel** [comment]
Yes, you can freely move between different firmwares and FPGA images on the USRP. The instructions at http://uhd.ettus.com will tell you how to download images and load them.

**Comment by ggamble22** [comment]
Sounds good, thank you.

**Comment by ggamble22** [comment]
@dkozel It worked perfectly. Still would be nice if the necessary file dependency bundle was on here or a modified version of the script that downloaded the necessary files individually instead of the current method of downloading it from another server.

**Comment by dkozel** [comment]
I'm glad to hear that. 

The images may actually already be included in the binary installer here. I am usually using development versions so have not looked and am not familiar. The FPGA images would add over 200 MB of size to the installer though so the current method helps keep that size down and a recent improvement to UHD's image downloader will make it simple to download only the required file.

Also I've just noticed that your URL is incorrect, the download page is:
http://www.gcndevelopment.com/gnuradio/downloads.htm

Did you have a different problem? If not, I think this issue can be closed @gnieboer

**Comment by ggamble22** [comment]
The link I provided is where the script is pulling it's download from. It appears to be grabbing a custom zip file with all the binaries in it instead of grabbing each one individually.  Everything as far as the UHD software works fine as well so adding the fpga images would not be neccessary. @gnieboer would need to update that url in the script (if the file was moved to the url you mentioned) to actually close  this issue. Thanks.

**Comment by ggamble22** [comment]
The full link for the first download the script fails at is http://www.gcndevelopment.com/gnuradio/downloads/sources/gnuradio_dependency_pack_v.7z to advoid confusion.

**Comment by gnieboer** [comment]
@dkozel, thanks for helping out.  I've been travelling all week.

@ggamble22 so it looks like the issue is in how the scripts are being invoked... the file download isn't working because the version number (1.3) isn't being appended after the _v .  This can happen is the setup scripts aren't run or found.

So can you tell me how you are calling the scripts?

You should be starting with ~RUNME_FIRST.ps1... that will set up all the paths are walk you through the options of downloading the dependencies or building everything from scratch.   I recommend cloning the repo to c:/gr_build as a root dir.

Please check that and let me know.

**Comment by ggamble22** [comment]
@gnieboer Sorry I haven't had the time to respond. I am probably moving over to running this in Linux but it would still be nice to have this working in case Windows is wanted. There have been a number of errors I have had to fix manually from the start. You may want to verify this by starting a build from the latest version of what is on the repo in a clean environment. Also, yes I can follow instructions and did run the file ~RUNME_FIRST.ps1. (Note: I am a Software Engineer and have some level of competency. Just not with Powershell though.) I did also try your suggestions.

One error for example was in the file Setup.ps, line 306. I needed to add `-BindingVariable "VersionInfo"` to fix an error it was complaining about. The problems I am having may be because of the version of Powershell I'm running. I did find I ad to install multiple versions of Powershell to get to a version that worked. I didn't want to just grab the latest because I was unsure if that would cause its own problems. 

Another useful item to add in your instructions is version numbers of the prerequisite software.

Thanks.

**Comment by gnieboer** [comment]
Yes, running the build from a clean VM environment is a standard part of my tests before release.  I suspect your problems may lie from running it on Windows 7?  I did not list that (Win 10 64-bit) as a pre-req in the readme, I will add it, as well as any other versions specific issues (Win10 comes w/ PS 5.0+ standard).  CMake has a specific version issue in the notes but I will add to the pre-req listing.

I am currently working on the 3.7.12 release (which includes updated UHD drivers), so hopefully that will obviate the need to build from source.

**Comment by ggamble22** [comment]
Ok, since it seems like a Windows issue, I will close my issue. Unfortunately this is a company project and we are stuck with Windows 7 for the time being. I can wait for the updated release. Thanks for the help.
