### ISSUE TITLE
Need to specify TLS version for powershell for wget.

### ISSUE THREAD

**Issue by mawelsh** [gnieboer/GNURadio_Windows_Build_Scripts#32]
Adding 

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

in setup.ps1 enables retrieving of pyzmq v14.7.0 in current from source build.

**Comment by gnieboer** [comment]
Thanks.  Will include.

**Comment by gnieboer** [comment]
So this code was actually already in setup.ps1, at the very end of the script.  I didn't have any problems pulling pyzmq.  Were you perhaps using an older version of repo?

**Comment by gnieboer** [comment]
Ah, that change was in master and hadn't been merged into maint.  Anyways, both are in sync now, thanks.
