### ISSUE TITLE
Failure retrieving libpng-1.6.29.tar

### ISSUE THREAD

**Issue by mawelsh** [gnieboer/GNURadio_Windows_Build_Scripts#33]
While running setup.py attempt to retrieve source for libpng returns:

wget : The remote server returned an error: (550) File unavailable (e.g., file not found, no access).
At C:\gr-build\scripts\Setup.ps1:80 char:9
+ ...             wget $toGet -OutFile "$archiveName$archiveExt" -UserAgent ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.FtpWebRequest:FtpWebRequest) [Invoke-WebRequest], WebExcep
   tion
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by mawelsh** [comment]
It looks like 1.6.34 should be the currently targeted version.

**Comment by gnieboer** [comment]
Yes, this is a common issue.  I'll update this weekend.

**Comment by gnieboer** [comment]
Updated scripts to v1.5 with numerous updated dependencies.
