### ISSUE TITLE
gr-display depends on gnuradio 3.8

### ISSUE THREAD

**Issue by Siebje** [gnieboer/GNURadio_Windows_Build_Scripts#36]
The current build does not work due to the fact that the latest master of gr-display depends on gnuradio 3.8. All in all, it seems safer to build a list of specific OOT module versions to download, rather than fetching the master from git.

**Comment by gnieboer** [comment]
Agreed, tagged versions are better.  When many of these were originally added the repo's didn't have tagged releases.
After I get a 3.8 version out the door, I'll go through all the OOT blocks and update them.

**Comment by gnieboer** [comment]
It now retrieves the last 3.7 release when building for 3.7.  The installer is in final build and test now.

**Comment by gnieboer** [comment]
v1.6 released
