### ISSUE TITLE
DLL name mismatch for libzmq

### ISSUE THREAD

**Issue by Vort** [gnieboer/GNURadio_Windows_Build_Scripts#37]
`gnuradio-zeromq.dll` is linked to `libzmq-v140-mt-4_3_1.dll`.
But installation contains no `libzmq-v140-mt-4_3_1.dll`, only `libzmq.dll`, which results in non-working ZeroMQ blocks.
Renaming of file fixes the problem, but it is better to fix this on your side.

**Comment by gnieboer** [comment]
Yes, this happened due a change in the way libzmq handles it's build
process.  I will indeed update the script.

**Comment by gnieboer** [comment]
Now everything links to the boost-style names and nothing is renamed.  Installer in final build and test now.

**Comment by gnieboer** [comment]
v1.6 released.
