### ISSUE TITLE
Site with dependency downloads is down

### ISSUE THREAD

**Issue by grebnetiew** [gnieboer/GNURadio_Windows_Build_Scripts#41]
It seems the [website with downloads for the dependencies](http://www.gcndevelopment.com) is down at the moment.
<details>
<summary>PowerShell error output</summary>
<p>
I modified the script slightly to make it print the URL before wgetting.

```
patch gnuradio_dependency_pack_v1.6...retrieving... http://www.gcndevelopment.com/gnuradio/downloads/sources/gnuradio_dependency_pack_v1.6.7z
wget : Unable to connect to the remote server
At C:\gr-build\scripts\Setup.ps1:181 char:3
+         wget $url -OutFile $toGet >> $Log
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
</p>
</details>

I created the issue mainly in case you were unaware - if this is a known/temporary problem, of course please feel free to close the issue :)

**Comment by gnieboer** [comment]
Sorry, transient issue, I didn't realize it.  Server back up now
