### ISSUE TITLE
The AMI is: GnuRadio Windows Build - ami-0ac7160e7f16f76ac     Can not get password ,can't use 

### ISSUE THREAD

**Issue by cql1983** [gnieboer/GNURadio_Windows_Build_Scripts#43]
The AMI is: GnuRadio Windows Build - ami-0ac7160e7f16f76ac  
Can not get password ,can't use.
please note the AMI password ,thinks

**Comment by gnieboer** [comment]
Sorry I just saw this issue.  I just confirmed the AMI is still there and the permissions are set for public.

Are you talking about the windows password after the instance is created?  If so, then that's available within AWS (it's unique to your instance) by right-clicking the instance and selecting "Windows Password"

**Comment by gnieboer** [comment]
Closed due to no further info available
