### ISSUE TITLE
Could not find Qt platform plugin "windows" in "C:\Program Files\GNURadio-3.8\bin\\plugins\platforms"

### ISSUE THREAD

**Issue by WA1CYB** [gnieboer/GNURadio_Windows_Build_Scripts#48]
Installed 3.8.1 without issues
Ran GRC 
Loaded a QT frequency sink in a flowgraph
Received this error message:
qt.qpa.plugin: Could not find Qt platform plugin "windows" in "C:\Program Files\GNURadio-3.8\bin\\plugins\platforms"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
>>> Done (return code -1073740791)

Is the \\plugins\platforms meant to be a UNC Network path?

**Comment by gnieboer** [comment]
Sorry, I could not duplicate.  
That directory should exist, having been created during install, not a UNC path.
There should be a file in that directory called "qwindows.dll".  Does that exist?

**Comment by WA1CYB** [comment]
The file exists. It appears your script put a double backslash, instead of a single one so the dll can't be found.
"C:\Program Files\GNURadio-3.8\bin\\plugins\platforms"  instead of  "C:\Program Files\GNURadio-3.8\bin\plugins\platforms"

In the "C:\Program Files\GNURadio-3.8\bin\plugins\platforms" directory there are the dll's:  qdirect2d.dll qwindows.dll qoffscreen.dll and qminimal.dll

    On Thursday, July 23, 2020, 04:03:29 PM EDT, Geof Nieboer <notifications@github.com> wrote:  
 
 


Sorry, I could not duplicate.
That directory should exist, having been created during install, not a UNC path.
There should be a file in that directory called "qwindows.dll". Does that exist?

**Comment by gnieboer** [comment]
Well, you can remove the / before /plugins in the run_gr.bat file, but that really shouldn't be having an effect.  Windows ignores the extra slashes when it finds them (enter cd c:\windows\\\\system to confirm).  

Those are the correct DLL's, so that part is good.

Let me know if the slash removal works.

**Comment by fksms** [comment]
The problem can be avoided by editing "C:\Program Files\GNURadio-3.8\bin\run_gr.bat".

"set QT_QPA_PLATFORM_PLUGIN_PATH=%~dp0\platforms"
"set QT_PLUGIN_PATH=%~dp0..\plugins"

Please change as above and save.
It should work correctly.

I made a pull request to solve this problem.
See #49.

**Comment by JochemsMatz** [comment]
I can confirm that this fix worked for me with GNU RC 3.8.1.0 under Windows 10.

**Comment by busycraftsman** [comment]
I have the same problem, I solved this problem by create a plugins folder in ".\GNURadio-3.8\bin",  and move the platforms folder into the plugins folder.   

I think this is a wrong package script cause this problem.

**Comment by gnieboer** [comment]
A new windows installer for 3.8.2 has been released [here](http://www.gcndevelopment.com/gnuradio/downloads/installers/v3.8.2.1/gnuradio-3.8.2.0-win64.msi) that sorts this path issue out.

If further issues are discovered, please open a new issue (as it should be a different root cause)

**Comment by AhmedKAwwad** [comment]
> The problem can be avoided by editing "C:\Program Files\GNURadio-3.8\bin\run_gr.bat".
> 
> "set QT_QPA_PLATFORM_PLUGIN_PATH=%~dp0\platforms"
> "set QT_PLUGIN_PATH=%~dp0..\plugins"
> 
> Please change as above and save.
> It should work correctly.
> 
> I made a pull request to solve this problem.
> See #49.

Actually worked for me  Thanks a lot
