### ISSUE TITLE
"USRP FM Receiver" does not work

### ISSUE THREAD

**Issue by fksms** [gnieboer/GNURadio_Windows_Build_Scripts#50]
https://github.com/gnieboer/GNURadio_Windows_Build_Scripts/blob/ba558efc14c196c7d865527a187103a8b1c2b3ff/wix/Product.wxs#L138-L145

"USRP FM Receiver" cannot be started because "usrp_wfm_rcv.py" does not exist.
Do you need this shortcut?

**Comment by gnieboer** [comment]
Good catch.  That application is not included in GR 3.8 because it is a WX app and WX is no longer supported in 3.8.  That shortcut should be removed (though I'd like to replace it with a similar basic app since that is a favorite place to start)

**Comment by gnieboer** [comment]
The shortcut has been removed in the latest installer, closing.
