### ISSUE TITLE
":Invalid argument" error problem fixed

### ISSUE THREAD

**Issue by fasthyun** [gnieboer/GNURadio_Windows_Build_Scripts#7]
sorry... I can't  speak English well

These two files have a bug...
1. gr-fft\lib\fft.cc  
2. gnuradio-runtime\lib\vmcircbuf_prefs.cc

Please check this URL... 
https://github.com/gnuradio/gnuradio/pull/820

**Comment by gnieboer** [comment]
This has been committed upstream and will be incorporated when the next GR release is posted.
